import{a as p,s as w,i as u}from"./assets/vendor-BtLqlKrq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))l(s);new MutationObserver(s=>{for(const a of s)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(s){const a={};return s.integrity&&(a.integrity=s.integrity),s.referrerPolicy&&(a.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?a.credentials="include":s.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(s){if(s.ep)return;s.ep=!0;const a=e(s);fetch(s.href,a)}})();p.defaults.baseURL="https://pixabay.com/api/";async function g(t,r=1){return(await p({params:{key:"46272240-cb3616e4f216aad50124ac1b5",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r}})).data}function m(t){if(t.length===0)throw new Error;return t.map(e=>`<li class="gallery-object">
    <a href='${e.largeImageURL}' class="simple-gal"><img src='${e.webformatURL}' class="gallery-image" alt='${e.tags}' /></a>
    <ul class="gallery-stats">
    <li class="gallery-stats-likes">Likes <span>${e.likes}</span></li>
    <li class="gallery-stats-views">Views <span>${e.views}</span></li>
    <li class="gallery-stats-comments">Comments <span>${e.comments}</span></li>
    <li class="gallery-stats-downloads">Downloads <span>${e.downloads}</span></li>
    </ul>
    </li>`).join("")}const d=document.querySelector("form"),n=document.querySelector(".gallery-list"),f=document.querySelector(".loader"),i=document.querySelector(".show-more");let o={searchInp:"",page:1,totalPages:null};const h=new w(".simple-gal",{captionsData:"alt"});function y(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}async function v(){try{i.classList.add("is-hidden"),y(),o.page++;const t=await g(o.searchInp,o.page);console.log(t),L(),n.insertAdjacentHTML("beforeend",m(t.hits)),h.refresh();const r=n.children[0].getBoundingClientRect();if(window.scrollBy({top:r.height*2,behavior:"smooth"}),o.page<o.totalPages)i.classList.remove("is-hidden");else throw new Error}catch(t){console.log(t),i.classList.add("is-hidden"),u.error({message:"We're sorry, but you've reached the end of search results."})}}async function b(t){t.preventDefault(),n.innerHTML="",o.page=1,y(),i.classList.contains("is-hidden")||i.classList.add("is-hidden");const r=d[0].value.trim().split(" ");o.searchInp=r.join("+"),console.log(r);try{const e=await g(r.join("+"));o.totalPages=Math.ceil(e.totalHits/15),console.log(o.totalPages),L(),n.insertAdjacentHTML("beforeend",m(e.hits)),h.refresh(),e.totalHits>15&&i.classList.remove("is-hidden")}catch{console.log(o.error),u.error({message:"Sorry, there are no images matching your search query. Please try again!"})}d.reset()}d.addEventListener("submit",b);i.addEventListener("click",v);
//# sourceMappingURL=index.js.map
