import{a as p,s as w,i as u}from"./assets/vendor-BtLqlKrq.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))l(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(s){if(s.ep)return;s.ep=!0;const o=e(s);fetch(s.href,o)}})();p.defaults.baseURL="https://pixabay.com/api/";async function g(t,a=1){return(await p({params:{key:"46272240-cb3616e4f216aad50124ac1b5",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:a}})).data}function m(t){if(t.length===0)throw new Error;return t.map(e=>`<li class="gallery-object">
    <a href='${e.largeImageURL}' class="simple-gal"><img src='${e.webformatURL}' class="gallery-image" alt='${e.tags}' /></a>
    <ul class="gallery-stats">
    <li class="gallery-stats-likes">Likes <span>${e.likes}</span></li>
    <li class="gallery-stats-views">Views <span>${e.views}</span></li>
    <li class="gallery-stats-comments">Comments <span>${e.comments}</span></li>
    <li class="gallery-stats-downloads">Downloads <span>${e.downloads}</span></li>
    </ul>
    </li>`).join("")}const d=document.querySelector("form"),n=document.querySelector(".gallery-list"),f=document.querySelector(".loader"),i=document.querySelector(".show-more");let r={searchInp:"",page:1,totalPages:null};const h=new w(".simple-gal",{captionsData:"alt"});function y(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}async function v(){try{i.classList.add("is-hidden"),y(),r.page++;const t=await g(r.searchInp,r.page);console.log(t),L(),n.insertAdjacentHTML("beforeend",m(t.hits)),h.refresh();const a=n.children[0].getBoundingClientRect();window.scrollBy({top:a.height*2,behavior:"smooth"}),r.page<r.totalPages?i.classList.remove("is-hidden"):u.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){console.log(t)}}async function b(t){t.preventDefault(),n.innerHTML="",r.page=1,y(),i.classList.contains("is-hidden")||i.classList.add("is-hidden");const a=d[0].value.trim().split(" ");r.searchInp=a.join("+"),console.log(a);try{const e=await g(a.join("+"));r.totalPages=Math.ceil(e.totalHits/15),console.log(r.totalPages),L(),n.insertAdjacentHTML("beforeend",m(e.hits)),h.refresh(),e.totalHits>15&&i.classList.remove("is-hidden")}catch{u.error({message:"Sorry, there are no images matching your search query. Please try again!"})}d.reset()}d.addEventListener("submit",b);i.addEventListener("click",v);
//# sourceMappingURL=index.js.map
