import{a as p,s as w,i as u}from"./assets/vendor-BtLqlKrq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))l(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(s){if(s.ep)return;s.ep=!0;const o=e(s);fetch(s.href,o)}})();p.defaults.baseURL="https://pixabay.com/api/";async function m(t,r=1){return(await p({params:{key:"46272240-cb3616e4f216aad50124ac1b5",q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r}})).data}function f(t){if(t.length===0)throw new Error(response);return t.map(e=>`<li class="gallery-object">
    <a href='${e.largeImageURL}' class="simple-gal"><img src='${e.webformatURL}' class="gallery-image" alt='${e.tags}' /></a>
    <ul class="gallery-stats">
    <li class="gallery-stats-likes">Likes <span>${e.likes}</span></li>
    <li class="gallery-stats-views">Views <span>${e.views}</span></li>
    <li class="gallery-stats-comments">Comments <span>${e.comments}</span></li>
    <li class="gallery-stats-downloads">Downloads <span>${e.downloads}</span></li>
    </ul>
    </li>`).join("")}const d=document.querySelector("form"),n=document.querySelector(".gallery-list"),h=document.querySelector(".loader"),a=document.querySelector(".show-more");let i={searchInp:"",page:1};const g=new w(".simple-gal",{captionsData:"alt"});function y(){h.classList.remove("is-hidden")}function L(){h.classList.add("is-hidden")}async function v(){try{a.classList.add("is-hidden"),y(),i.page++;const t=await m(i.searchInp,i.page);console.log(t),L(),a.classList.remove("is-hidden"),n.insertAdjacentHTML("beforeend",f(t.hits)),g.refresh();const r=n.children[0].getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}catch(t){console.log(t),a.classList.add("is-hidden"),u.error({message:"We're sorry, but you've reached the end of search results."})}}async function b(t){t.preventDefault(),n.innerHTML="",i.page=1,y(),a.classList.contains("is-hidden")||a.classList.add("is-hidden");const r=d[0].value.trim().split(" ");i.searchInp=r.join("+"),console.log(r);try{const e=await m(r.join("+"));console.log(e),L(),n.insertAdjacentHTML("beforeend",f(e.hits)),g.refresh(),a.classList.remove("is-hidden")}catch(e){console.log(e),u.error({message:"Sorry, there are no images matching your search query. Please try again!"})}d.reset()}d.addEventListener("submit",b);a.addEventListener("click",v);
//# sourceMappingURL=index.js.map
